name: Run Autoclaim

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *'

concurrency:
  group: 'pythonC'  # 设置唯一的组ID
  cancel-in-progress: true 

jobs:
  Notpixel:
    runs-on: ubuntu-latest
    continue-on-error: true
    timeout-minutes: 150
    if: true
    env:
      WP_CONFIG: ${{ secrets.WARP_CONFIG }}
      SESSION_CONFIG: ${{ secrets.SESSION_CONFIG }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.6

      - name: Connect InnerWeb
        run: |
          mkdir app
          mkdir app/warp
          cd app/warp
          wget https://github.com/Suyunmeng/pfile/releases/download/public-packages/web.js
          wget ${{ env.WP_CONFIG }}
          chmod +x web.js test.json
          nohup ./web.js -c test.json &

      - name: Install dependencies
        run: |
          mkdir app/11
          cd app/11
          wget ${{ env.SESSION_CONFIG }}/11/11.zip
          unzip 11.zip
          rm -rf 11.zip
          chmod -R +x ./
          bash build.sh

      - name: Run Notpixels
        run: |
          cd app/11
          bash run.sh

  Hrum:
    runs-on: ubuntu-latest
    continue-on-error: true
    timeout-minutes: 150
    env:
      WP_CONFIG: ${{ secrets.WARP_CONFIG }}
      SESSION_CONFIG: ${{ secrets.SESSION_CONFIG }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.6

      - name: Connect InnerWeb
        run: |
          mkdir app
          mkdir app/warp
          cd app/warp
          wget https://github.com/Suyunmeng/pfile/releases/download/public-packages/web.js
          wget ${{ env.WP_CONFIG }}
          chmod +x web.js test.json
          nohup ./web.js -c test.json &

      - name: Install dependencies
        run: |
          mkdir app/12
          cd app/12
          wget ${{ env.SESSION_CONFIG }}/12/12.zip
          unzip 12.zip
          rm -rf 12.zip
          chmod -R +x ./
          bash build.sh

      - name: Run Hrums
        run: |
          cd app/12
          bash run.sh
