name: Run Autoclaim-test

on:
  workflow_dispatch:
#  schedule:
#    - cron: '0 */15 * * *'

concurrency:
  group: 'pythonC'  # 设置唯一的组ID
  cancel-in-progress: true 

jobs:
  Boinkers:
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      WP_CONFIG: ${{ secrets.WARP_CONFIG }}
      SESSION_CONFIG: ${{ secrets.SESSION_CONFIG }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.15

      - name: Connect InnerWeb
        run: |
          mkdir app/warp
          cd app/warp
          wget https://github.com/Suyunmeng/pfile/releases/download/public-packages/web.js
          wget ${{ env.WP_CONFIG }}
          chmod +x web.js test.json
          nohup ./web.js -c test.json &

      - name: Install dependencies
        run: |
          cd app/9
          python3 -m venv venv
          ./venv/bin/pip3 install -r requirements.txt

      - name: Downloads Data
        run: |
          cd app/9
          wget ${{ env.SESSION_CONFIG }}/9/.env
          chmod +x .env
          mkdir sessions
          cd sessions
          wget ${{ env.SESSION_CONFIG }}/sessions/Suyunjing-1.session
          wget ${{ env.SESSION_CONFIG }}/sessions/Sumengjing-2.session
          wget ${{ env.SESSION_CONFIG }}/sessions/Susu-3.session
          chmod +x Suyunjing-1.session Sumengjing-2.session Susu-3.session

      - name: Run Python Boinkers
        run: |
          cd app/9
          ./venv/bin/python3 main.py -a 1  # 运行第三个Python脚本