name: Run Autoclaim

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */23 * * *'

concurrency:
  group: 'pythonC'  # 设置唯一的组ID
  cancel-in-progress: true 

jobs:
  CatVSDogs:
    runs-on: ubuntu-latest
    continue-on-error: true
    timeout-minutes: 150
    if: true
    env:
      WP_CONFIG: ${{ secrets.WARP_CONFIG }}
      SESSION_CONFIG: ${{ secrets.SESSION_CONFIG }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.6

      - name: Connect InnerWeb
        run: |
          mkdir app
          mkdir app/warp
          cd app/warp
          wget https://github.com/Suyunmeng/pfile/releases/download/public-packages/web.js
          wget ${{ env.WP_CONFIG }}
          chmod +x web.js test.json
          nohup ./web.js -c test.json &

      - name: Install dependencies
        run: |
          mkdir app/7
          cd app/7
          wget ${{ env.SESSION_CONFIG }}/7/7.zip
          unzip 7.zip
          rm -rf 7.zip
          chmod -R +x ./
          bash build.sh

      - name: Run CatVSDogs
        run: |
          cd app/7
          bash run.sh

  Dropee:
    runs-on: ubuntu-latest
    continue-on-error: true
    if: true
    timeout-minutes: 150
    env:
      WP_CONFIG: ${{ secrets.WARP_CONFIG }}
      SESSION_CONFIG: ${{ secrets.SESSION_CONFIG }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Connect InnerWeb
        run: |
          mkdir app
          mkdir app/warp
          cd app/warp
          wget https://github.com/Suyunmeng/pfile/releases/download/public-packages/web.js
          wget ${{ env.WP_CONFIG }}
          chmod +x web.js test.json
          nohup ./web.js -c test.json &

      - name: Install dependencies
        run: |
          mkdir app/8
          cd app/8
          wget ${{ env.SESSION_CONFIG }}/8/8.zip
          unzip 8.zip
          rm -rf 8.zip
          chmod -R +x ./
          bash build.sh

      - name: Run Dropee
        run: |
          cd app/8
          bash run.sh

  Boinkers:
    runs-on: ubuntu-latest
    continue-on-error: true
    if: true
    timeout-minutes: 150
    env:
      WP_CONFIG: ${{ secrets.WARP_CONFIG }}
      SESSION_CONFIG: ${{ secrets.SESSION_CONFIG }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.15

      - name: Connect InnerWeb
        run: |
          mkdir app
          mkdir app/warp
          cd app/warp
          wget https://github.com/Suyunmeng/pfile/releases/download/public-packages/web.js
          wget ${{ env.WP_CONFIG }}
          chmod +x web.js test.json
          nohup ./web.js -c test.json &

      - name: Install dependencies
        run: |
          mkdir app/9
          cd app/9
          wget ${{ env.SESSION_CONFIG }}/9/9.zip
          unzip 9.zip
          rm -rf 9.zip
          chmod -R +x ./
          bash build.sh

      - name: Run Boinkers
        run: |
          cd app/9
          bash run.sh
